### ISSUE TITLE
Emote failed to start after upgrading to 4.0.1

### ISSUE THREAD

**Issue by murlock** [tom-james-watson/Emote#121]
I'm not sure if it is related to gnome snap not updated

```
/snap/emote/23/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas: symbol lookup error: /snap/emote/23/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas: undefined symbol: g_task_set_static_name
ERROR: compile_schemas /snap/emote/23/gnome-platform/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas exited abnormally with status 127

Cannot load module /snap/emote/23/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: /snap/emote/23/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
/snap/emote/23/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so does not export GTK+ IM module API: /snap/emote/23/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
ERROR: /snap/emote/23/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 exited abnormally with status 1
Running on an Ubuntu-derived system, trying to fix font issue.
```
or if there is other issue due to update 
```
juil. 06 08:42:44 T14 emote.desktop[4229]: Traceback (most recent call last):
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/lib/python3.6/site-packages/emote/__init__.py", line 75, in handle_accelerator
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/lib/python3.6/site-packages/emote/__init__.py", line 94, in create_picker_window
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/lib/python3.6/site-packages/emote/picker.py", line 46, in __init__
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/lib/python3.6/site-packages/emote/picker.py", line 77, in init_header
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/lib/python3.6/site-packages/emote/picker.py", line 135, in init_skintone_button
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/lib/python3.6/site-packages/emote/user_data.py", line 127, in load_skintone
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/usr/lib/python3.6/shelve.py", line 243, in open
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/usr/lib/python3.6/shelve.py", line 227, in __init__
juil. 06 08:42:44 T14 emote.desktop[4229]:   File "/snap/emote/19/usr/lib/python3.6/dbm/__init__.py", line 94, in open
juil. 06 08:42:44 T14 emote.desktop[4229]: _dbm.error: [Errno 13] Permission denied
```

I've tried to uninstall reinstall without success.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

$ sudo snap list
Name               Version                     Rev    Tracking       Publisher          Notes
bare               1.0                         5      latest/stable  canonical✓         base
chromium           114.0.5735.198              2529   latest/stable  canonical✓         -
core18             20230530                    2785   latest/stable  canonical✓         base
core20             20230622                    1974   latest/stable  canonical✓         base
core22             20230612                    766    latest/stable  canonical✓         base
cups               2.4.6-2                     974    latest/stable  openprinting✓      -
emote              4.0.1                       23     latest/stable  tom-james-watson   -
firefox            115.0-2                     2850   latest/stable  mozilla✓           -
gnome-3-28-1804    3.28.0-19-g98f9e67.98f9e67  198    latest/stable  canonical✓         -
gnome-3-38-2004    0+git.6f39565               140    latest/stable  canonical✓         -
gnome-42-2204      0+git.ff35a85               111    latest/stable  canonical✓         -
gtk-common-themes  0.1-81-g442e511             1535   latest/stable  canonical✓         -
snapd              2.59.5                      19457  latest/stable  canonical✓         snapd
```

**Comment by murlock** [comment]
Issue has disappeared after a reboot, not sure what it is the root cause however.
