### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by AnilSonix** [tom-james-watson/Emote#5]
on Ubuntu 20.04
```
anil@dev:~/Desktop$ emote 

(emote:5616): Gtk-WARNING **: 10:16:31.200: Locale not supported by C library.
	Using the fallback 'C' locale.

(emote:5616): GdkPixbuf-WARNING **: 10:16:31.253: Cannot open pixbuf loader module file '/home/anil/snap/emote/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/anil/snap/emote/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
Gtk-Message: 10:16:31.301: Failed to load module "canberra-gtk-module"
Launching emote daemon

(emote:5616): Gtk-WARNING **: 10:16:31.309: Theme parsing error: style.css:22:11: Not using units is deprecated. Assuming 'px'.

(emote:5616): Gtk-WARNING **: 10:16:31.309: Theme parsing error: style.css:27:19: Not using units is deprecated. Assuming 'px'.
Traceback (most recent call last):
  File "/snap/emote/7/lib/python3.6/site-packages/emote/__init__.py", line 67, in do_activate
    self.start_daemon()
  File "/snap/emote/7/lib/python3.6/site-packages/emote/__init__.py", line 23, in start_daemon
    emojis.init()
  File "/snap/emote/7/lib/python3.6/site-packages/emote/emojis.py", line 26, in init
    emojis = json.load(f)
  File "/snap/emote/7/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/snap/emote/7/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 96: ordinal not in range(128)
anil@dev:~/Desktop$ 

```

**Comment by AnilSonix** [comment]
Reinstalled it, then it worked

**Comment by tom-james-watson** [comment]
Yeah I'm not sure what happened there. I would guess installation failed somehow and the json file of emojis it's trying to load is empty.

**Comment by worldofgeese** [comment]
@tom-james-watson had the same issue not fixed by a reinstall:
```
Launching emote daemon
Traceback (most recent call last):
  File "/snap/emote/19/lib/python3.6/site-packages/emote/__init__.py", line 104, in do_activate
    self.start_daemon()
  File "/snap/emote/19/lib/python3.6/site-packages/emote/__init__.py", line 33, in start_daemon
    emojis.init()
  File "/snap/emote/19/lib/python3.6/site-packages/emote/emojis.py", line 248, in init
    for row in reader:
  File "/snap/emote/19/usr/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/snap/emote/19/usr/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/snap/emote/19/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 176: ordinal not in range(128)
```
