### ISSUE TITLE
bug: emote crashes

### ISSUE THREAD

**Issue by evilsh3ll** [tom-james-watson/Emote#94]
I get the following error by running the latest version of emote in an updated archlinux machine:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/emote", line 33, in <module>
    sys.exit(load_entry_point('Emote==3.0.3', 'gui_scripts', 'emote')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/emote", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for Emote

```
I use this version that was updated yesterday https://aur.archlinux.org/packages/emote

**Comment by tom-james-watson** [comment]
The arch package is not maintained by me, so it's probably best to report issues directly on AUR? I've never used AUR, so I'm not sure if that's the norm. @lkrms?

**Comment by lkrms** [comment]
Arch just moved from Python 3.10 to 3.11, so if you’ve updated your official packages, any AUR packages that depend on Python will need to be rebuilt.

I bumped the release version of Emote to trigger a rebuild yesterday, so you should only need to sync your AUR packages and this will be resolved.

**Comment by evilsh3ll** [comment]
Thank you
