### ISSUE TITLE
"manimpango" error when trying to launch emote

### ISSUE THREAD

**Issue by victoriastuart** [tom-james-watson/Emote#95]
In case anyone else gets the `manimpango` error when trying to launch `emote`.

**ISSUE**

```
  [victoria@victoria ~]$ date
    Fri May 19 04:50:01 PM PDT 2023

  [victoria@victoria ~]$ yay -Ss emote | grep -w emote
    aur/emote 3.1.0-2 (+25 0.74) (Installed)

  [victoria@victoria ~]$

  [victoria@victoria ~]$ emote

    Traceback (most recent call last):
      File "/usr/bin/emote", line 33, in <module>
        sys.exit(load_entry_point('Emote==3.1.0', 'gui_scripts', 'emote')())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/bin/emote", line 25, in importlib_load_entry_point
        return next(matches).load()
              ^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
        module = import_module(match.group('module'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/usr/lib/python3.11/site-packages/emote/__init__.py", line 4, in <module>
        import manimpango
    ModuleNotFoundError: No module named 'manimpango'

  [victoria@victoria ~]$ yay -Ss manimpango

    aur/python-manimpango 0.4.3-1 (+13 0.73) (Installed)
      C binding for Pango using Cython used in Manim to render (non-LaTeX) text.

  [victoria@victoria ~]$
```

**SOLUTION**

```
  [victoria@victoria ~]$ sudo vim /usr/lib/python3.11/site-packages/emote/__init__.py
    [sudo] password for victoria:

    ## COMMENTED OUT these two lines:
    ##    # import manimpango
    ##    # manimpango.register_font(f"{config.static_root}/NotoColorEmoji.ttf")

  [victoria@victoria ~]$
```

**Comment by ZimbiX** [comment]
Can we reopen this issue? This is still a problem.

After installing from AUR, I still have to comment out the `import manimpango` line in `/usr/lib/python3.11/site-packages/emote/__init__.py`.

The other line is no longer present, and I can't see any other references to `manimpango` - so it looks like the dependency can be removed entirely?

**Comment by tom-james-watson** [comment]
I've made https://github.com/tom-james-watson/Emote/issues/126 to remove the unused requirement, but really this is a downstream packaging issue, because it works fine via the official installation methods.
